# Numpy Basics <hr style="border:2.5px solid #554988"></hr>

Data Analyst: Jaymark S. Arlante <br>
Department: Electrical Engineering

In [26]:
# imports and packages
import numpy as np
from scipy import stats

# 1D Array

In [29]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [34]:
my_array = np.array([
    [1,2,3],
    [4,5,6]])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
my_array = my_array.T

In [38]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [42]:
# add by row
np.sum(my_array,axis=0)

array([ 6, 15])

In [43]:
# add by column
np.sum(my_array,axis=1)

array([5, 7, 9])

# Measure of Central Tendency

In [3]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [5]:
fruits_mean = np.mean(fruits)
fruits_mean

123.0

In [6]:
fruits_median = np.median(fruits)
fruits_median

120.0

In [7]:
fruits_sorted = np.sort(fruits)
fruits_sorted

array([ 60,  85, 120, 150, 200])

In [10]:
stats.mode(fruits)

ModeResult(mode=60, count=1)

# Jaguar vs Panther

## Jaguar

In [13]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [21]:
jag_mean = np.mean(jaguar)
jag_mean

9.399999999999999

In [22]:
jag_median = np.median(jaguar)
jag_median

9.8

In [23]:
stats.mode(jaguar)

ModeResult(mode=9.8, count=2)

In [57]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)

range_jag = max_jag - min_jag
range_jag

8.0

In [56]:
# Q1
q1_jag = np.percentile(jaguar,25)
q1_jag

9.4

In [54]:
#Q2 (Median)
q2_jag = np.percentile(jaguar,50)
q2_jag

9.8

In [51]:
# Q3
q3_jag = np.percentile(jaguar,75)
q3_jag

10.45

In [68]:
# IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

1.049999999999999

In [69]:
# sample variance
var_jag = np.var(jaguar,ddof=1)
var_jag

4.86

In [72]:
# sample standard deviation
std_jag = np.std(jaguar,ddof=1)
std_jag

2.2045407685048604

## Panther

In [15]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [20]:
pan_mean = np.mean(panther)
pan_mean

10.75

In [24]:
pan_median = np.median(panther)
pan_median

9.55

In [25]:
stats.mode(panther)

ModeResult(mode=9.1, count=3)

In [58]:
max_pan = np.max(panther)
min_pan = np.min(panther)

range_pan = max_pan - min_pan
range_pan

10.9

In [63]:
# Q1
q1_pan = np.percentile(panther,25)
q1_pan

9.125

In [65]:
# Q2 (Median)
q2_pan = np.percentile(panther,50)
q2_pan

9.55

In [66]:
# Q3
q3_pan = np.percentile(panther,75)
q3_pan

10.625

In [67]:
# IQR
iqr_pan = q3_pan - q1_pan
iqr_pan

1.0749999999999993

In [70]:
# sample variance
var_pan = np.var(panther,ddof=1)
var_pan

11.082777777777777

In [74]:
# sample standard deviation
std_pan = np.std(panther,ddof=1)
std_pan

3.3290806204983645

# Voltage Response

In [11]:
voltage = np.array([
    [1,2,3,4,5,6,7,8],
    [12,5,9.1,3.3,24,18.5,15.2,np.nan],
    [2.8,4.5,6,9,11.7,14.8,17.3,20]
])
voltage

array([[ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ],
       [12. ,  5. ,  9.1,  3.3, 24. , 18.5, 15.2,  nan],
       [ 2.8,  4.5,  6. ,  9. , 11.7, 14.8, 17.3, 20. ]])

# Measures of Variability